swagger: "2.0"
info:
  version: "0.0.1"
  title: pdd API
# during dev, should point to your local machine
host: localhost:10010
# basePath prefixes all resource paths 
basePath: /
# 
schemes:
  # tip: remove http to make production-grade
  - http
  - https
# format of bodies a client can send (Content-Type)
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /banners:
    get:
      description: "the slideshow of home"
      operationId: "GetBanners"
      parameters: []
      responses:
        200:
          description: "successfully"
          schema: 
            type: "array"
            items: 
              $ref: "#/definitions/banner"
      x-swagger-router-controller:
        "GetBanners"
        
  /tabs:
    get:
      description: "the top navigation tabs"
      operationId: "GetTabs"
      parameters: []
      responses:
        200:
          description: "successfully"
          schema: 
            type: "array"
            items: 
              $ref: "#/definitions/tab"
      x-swagger-router-controller:
        "GetTabs"
        
  /channels:
    get:
      description: "channels"
      operationId: "GetChannels"
      parameters: []
      responses:
        200:
          description: "successfully"
          schema: 
            type: "array"
            items: 
              $ref: "#/definitions/channel"
      x-swagger-router-controller:
        "GetChannels"
        
  /ads:
    get:
      description: "Rerieve a single todo by id"
      operationId: "FindAdsById"
      parameters:
      - name: "categories_like"
        in: "query"
        description: "category to get picture"
        required: true
        type: "string"
      responses:
        200:
          description: "successfully"
          schema: 
            type: "array"
            items: 
              $ref: "#/definitions/ad"
      x-swagger-router-controller:
        "FindAdsById"
  
  /products:
    get:
      description: "products"
      operationId: "FindProById"
      parameters:
      - name: "categories_like2"
        in: "query"
        description: "category to get products list"
        required: true
        type: "string"
      responses:
        200:
          description: "successfully"
          schema: 
            type: "array"
            items: 
              $ref: "#/definitions/product"
      x-swagger-router-controller:
        "FindProById"
        
  /productVariants:
    get:
      description: "products"
      operationId: "FindProVarById"
      parameters:
      - name: "productId"
        in: "query"
        description: "category to get variants list"
        required: true
        type: "integer"
      responses:
        200:
          description: "successfully"
          schema: 
            type: "array"
            items: 
              $ref: "#/definitions/productVariant"
      x-swagger-router-controller:
        "FindProVarById"
        
  /profile:
     get:
      description: "profile"
      operationId: "GetProfile"
      parameters: []
      responses:
        200:
          description: "successfully"
          schema: 
            $ref: "#/definitions/profile"
      x-swagger-router-controller:
        "GetProfile"
    
  /swagger:
    x-swagger-pipe: swagger_raw
# complex objects have schema definitions
definitions:
  banner:
    type: "object"
    properties:
      id: 
        type: "integer"
      imgUrl:
        type: "string"
      link:
        type: "string"
      caption:
        type: "string"
        
  tab:
    type: "object"
    properties:
      id: 
        type: "integer"
      title: 
        type: "string"
      link: 
        type: "string"
        
  channel:
    type: "object"
    properties:
      id:
        type: "integer"
      title: 
        type: "string"
      icon: 
        type: "string"
      link: 
        type: "string"
        
  ad:
    type: "object"
    properties:
      imageUrl:
        type: "string"
      link: 
        type: "string"
      categories:
        type: "array"
        items: 
          type: "string"
          
  product:
    type: "object"
    properties:
      id:
        type: "integer"
      title:
        type: "string"
      imageUrl: 
        type: "string"
      tags:
        type: "array"
        items:
          type: "string"
      price:
        type: "number"
      priceDesc:
        type: "string"
      buyerAvatars:
        type: "array"
        items:
          type: "string"
      categories:
        type: "array"
        items:
          type: "string"
    
  productVariant:
    type: "object"
    properties:
      id:
        type: "integer"
      producId:
        type: "integer"
      name:
        type: "string"
      price:
        type: "number"
      listPrice:
        type: "number"
      productVariantImages:
        type: "array"
        items:
          type: "object"
      product:
        type: "object"
        properties:
          id:
            type: "integer"
          title:
            type: "string"
          imageUrl: 
            type: "string"
          tags:
            type: "array"
            items:
              type: "string"
          price:
            type: "number"
          priceDesc:
            type: "string"
          buyerAvatars:
            type: "array"
            items:
              type: "string"
          categories:
            type: "array"
            items:
              type: "string"
    
  profile:
    type: "object"
    properties:
      name:
        type: "string"
      avatar:
        type: "string"
      gender:
        type: "integer"
      address:
        type: "string"
      birthday:
        type: "string"
      username:
        type: "string"

  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
